### ISSUE TITLE
Doesn't Find directorys properly in windows.

### ISSUE THREAD

**Issue by jampot5000** [bibby/botzilla#1]
I have fixed this by changing BZ_PATH to define('BZ_PATH',dirname(**FILE**).'/../');

**Comment by jampot5000** [comment]
it has changed what it put there should be an underscore before and after file.

**Comment by bibby** [comment]
The absolute path of the botzilla installation will vary across checkouts, and was meant to be set by the user as part of their initial configuration. Using the file's own location does, however, remove that step, although I'd do a double dirname for readability should the path ever be printed.

```
define( "BZ_PATH", dirname( dirname( __FILE__ ) ) ."/" );
```
